---
- name: Bootstrap the system
  raw: (test -e /usr/bin/python && test -d /etc/ca-certificates) || (apt -y update && apt install -y python-minimal python-apt ca-certificates unzip)
- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx
    - php-fpm
    - php-gd
    - php-mysql
    - php-curl
    - php-xml
    - php-zip
    - php-intl
    - php-mbstring
    - php-json
    - php-bz2
    - php-apcu
    - imagemagick
    - php-imagick
    - mariadb-server
    - python-mysqldb
    - dehydrated
    - sudo

- name: Copy default nginx configuration
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default owner=root group=root mode=0400
  notify:
    - Restart nginx

- name: Copy PHP-configuration
  template: src=www.conf.j2 dest=/etc/php/7.0/fpm/pool.d/www.conf owner=root group=root mode=0400
  notify:
    - Restart PHP

- meta: flush_handlers

- name: Copy dehydrated-configuration
  template: src=config.j2 dest=/etc/dehydrated/config owner=root group=root mode=0400
- template: src=domains.txt.j2 dest=/etc/dehydrated/domains.txt owner=root group=root mode=0400

- name: Generate TLS-certificates
  file: name=/var/www/dehydrated/ state=directory
- shell: /usr/bin/dehydrated -c
- file: name=/etc/nginx/ssl state=directory owner=root group=root mode=0500
- file: src=/var/lib/dehydrated/certs/{{ hostname }}/fullchain.pem dest=/etc/nginx/ssl/{{ hostname }}.crt state=link
- file: src=/var/lib/dehydrated/certs/{{ hostname }}/privkey.pem dest=/etc/nginx/ssl/{{ hostname }}.key state=link

- name: Copy Nextcloud-config for nginx
  template: src=nextcloud.j2 dest=/etc/nginx/sites-enabled/nextcloud owner=root group=root mode=0400
  notify:
    - Restart nginx

- name: Secure MariaDB
  mysql_user: name=root password={{ db_root_password }} host='localhost'
- name: Create user / database
  mysql_db: name={{ db_name }} state=present
- mysql_user: name={{ db_username }} password={{ db_password }} priv={{ db_name}}.*:ALL host='localhost' state=present

- name: Download / unpack Nextcloud
  unarchive: src=https://download.nextcloud.com/server/releases/latest.zip dest=/var/www/ remote_src=yes
  creates: /var/www/nextcloud
- file: path=/var/www/nextcloud owner=www-data group=www-data recurse=yes
